import Foundation
import SwiftData

@Model
public final class ShoppingItem {
    public var id: UUID?
    public var name: String?
    public var category: ShoppingCategory?
    public var quantity: String? // e.g. "2 bags", "1 packet", "3 lbs"
    public var isPurchased: Bool = false
    public var isAutoGenerated: Bool = false
    public var notes: String?
    public var garden: Garden?
    public var createdDate: Date?

    public init(
        name: String,
        category: ShoppingCategory,
        quantity: String? = nil,
        isAutoGenerated: Bool = false
    ) {
        self.id = UUID()
        self.name = name
        self.category = category
        self.quantity = quantity
        self.isAutoGenerated = isAutoGenerated
        self.createdDate = Date()
    }
}

// MARK: - ShoppingCategory

public enum ShoppingCategory: String, CaseIterable, Codable, Sendable {
    case seeds
    case soilAmendments
    case tools
    case containers
    case fertilizer
    case pestControl
    case other

    public var displayName: String {
        switch self {
        case .seeds: "Seeds"
        case .soilAmendments: "Soil & Amendments"
        case .tools: "Tools"
        case .containers: "Containers"
        case .fertilizer: "Fertilizer"
        case .pestControl: "Pest Control"
        case .other: "Other"
        }
    }

    public var icon: String {
        switch self {
        case .seeds: "leaf.fill"
        case .soilAmendments: "mountain.2.fill"
        case .tools: "wrench.and.screwdriver.fill"
        case .containers: "cube.box.fill"
        case .fertilizer: "drop.triangle.fill"
        case .pestControl: "ladybug.fill"
        case .other: "ellipsis.circle.fill"
        }
    }
}
