import Foundation
@testable import GrowWiseModels
import Testing

struct ShoppingItemTests {
    // MARK: - Initialization

    @Test("Init sets name, category, and generates non-nil UUID")
    func initSetsNameCategoryAndID() {
        let item = ShoppingItem(name: "Tomato seeds", category: .seeds)
        #expect(item.name == "Tomato seeds")
        #expect(item.category == .seeds)
        #expect(item.id != nil)
    }

    @Test("Init sets quantity when provided")
    func initSetsQuantityWhenProvided() {
        let item = ShoppingItem(name: "Potting soil", category: .soilAmendments, quantity: "2 bags")
        #expect(item.quantity == "2 bags")
    }

    @Test("Init sets isAutoGenerated to true when specified")
    func initSetsIsAutoGeneratedTrue() {
        let item = ShoppingItem(name: "Garden trowel", category: .tools, isAutoGenerated: true)
        #expect(item.isAutoGenerated == true)
    }

    @Test("Init records createdDate as approximately now")
    func initRecordsCreatedDateAsNow() throws {
        let before = Date()
        let item = ShoppingItem(name: "Fertilizer", category: .fertilizer)
        let after = Date()
        let createdDate = try #require(item.createdDate)
        #expect(createdDate >= before)
        #expect(createdDate <= after)
    }

    @Test("Each init call produces a unique UUID")
    func initProducesUniqueIDs() {
        let a = ShoppingItem(name: "Item A", category: .seeds)
        let b = ShoppingItem(name: "Item B", category: .seeds)
        #expect(a.id != b.id)
    }

    // MARK: - Default Values

    @Test("isPurchased defaults to false")
    func isPurchasedDefaultsFalse() {
        let item = ShoppingItem(name: "Pruning shears", category: .tools)
        #expect(item.isPurchased == false)
    }

    @Test("isAutoGenerated defaults to false when not specified")
    func isAutoGeneratedDefaultsFalse() {
        let item = ShoppingItem(name: "Containers", category: .containers)
        #expect(item.isAutoGenerated == false)
    }

    // MARK: - Optional Properties Nil by Default

    @Test("quantity is nil when not provided")
    func quantityNilByDefault() {
        let item = ShoppingItem(name: "Ladybug spray", category: .pestControl)
        #expect(item.quantity == nil)
    }

    @Test("notes is nil by default")
    func notesNilByDefault() {
        let item = ShoppingItem(name: "Compost", category: .soilAmendments)
        #expect(item.notes == nil)
    }

    @Test("garden is nil by default")
    func gardenNilByDefault() {
        let item = ShoppingItem(name: "Watering can", category: .tools)
        #expect(item.garden == nil)
    }

    // MARK: - isPurchased Toggle

    @Test("isPurchased can be toggled to true")
    func toggleIsPurchasedToTrue() {
        let item = ShoppingItem(name: "Seeds", category: .seeds)
        item.isPurchased = true
        #expect(item.isPurchased == true)
    }

    @Test("isPurchased can be toggled back to false after being purchased")
    func toggleIsPurchasedBackToFalse() {
        let item = ShoppingItem(name: "Seeds", category: .seeds)
        item.isPurchased = true
        item.isPurchased = false
        #expect(item.isPurchased == false)
    }

    // MARK: - ShoppingCategory Coverage

    @Test("ShoppingCategory has exactly 7 cases")
    func shoppingCategoryHasSevenCases() {
        #expect(ShoppingCategory.allCases.count == 7)
    }

    @Test("ShoppingCategory allCases contains all expected raw values")
    func shoppingCategoryAllCasesContainsExpectedRawValues() {
        let expected: Set = ["seeds", "soilAmendments", "tools", "containers", "fertilizer", "pestControl", "other"]
        let actual = Set(ShoppingCategory.allCases.map(\.rawValue))
        #expect(actual == expected)
    }

    // MARK: - ShoppingCategory displayName

    @Test("seeds displayName is Seeds")
    func seedsDisplayName() {
        #expect(ShoppingCategory.seeds.displayName == "Seeds")
    }

    @Test("soilAmendments displayName is Soil & Amendments")
    func soilAmendmentsDisplayName() {
        #expect(ShoppingCategory.soilAmendments.displayName == "Soil & Amendments")
    }

    @Test("tools displayName is Tools")
    func toolsDisplayName() {
        #expect(ShoppingCategory.tools.displayName == "Tools")
    }

    @Test("containers displayName is Containers")
    func containersDisplayName() {
        #expect(ShoppingCategory.containers.displayName == "Containers")
    }

    @Test("fertilizer displayName is Fertilizer")
    func fertilizerDisplayName() {
        #expect(ShoppingCategory.fertilizer.displayName == "Fertilizer")
    }

    @Test("pestControl displayName is Pest Control")
    func pestControlDisplayName() {
        #expect(ShoppingCategory.pestControl.displayName == "Pest Control")
    }

    @Test("other displayName is Other")
    func otherDisplayName() {
        #expect(ShoppingCategory.other.displayName == "Other")
    }

    @Test("every ShoppingCategory has a non-empty displayName")
    func everyShoppingCategoryHasNonEmptyDisplayName() {
        for category in ShoppingCategory.allCases {
            #expect(!category.displayName.isEmpty)
        }
    }

    // MARK: - ShoppingCategory icon

    @Test("seeds icon is leaf.fill")
    func seedsIcon() {
        #expect(ShoppingCategory.seeds.icon == "leaf.fill")
    }

    @Test("soilAmendments icon is mountain.2.fill")
    func soilAmendmentsIcon() {
        #expect(ShoppingCategory.soilAmendments.icon == "mountain.2.fill")
    }

    @Test("tools icon is wrench.and.screwdriver.fill")
    func toolsIcon() {
        #expect(ShoppingCategory.tools.icon == "wrench.and.screwdriver.fill")
    }

    @Test("containers icon is cube.box.fill")
    func containersIcon() {
        #expect(ShoppingCategory.containers.icon == "cube.box.fill")
    }

    @Test("fertilizer icon is drop.triangle.fill")
    func fertilizerIcon() {
        #expect(ShoppingCategory.fertilizer.icon == "drop.triangle.fill")
    }

    @Test("pestControl icon is ladybug.fill")
    func pestControlIcon() {
        #expect(ShoppingCategory.pestControl.icon == "ladybug.fill")
    }

    @Test("other icon is ellipsis.circle.fill")
    func otherIcon() {
        #expect(ShoppingCategory.other.icon == "ellipsis.circle.fill")
    }

    @Test("every ShoppingCategory has a non-empty icon name")
    func everyShoppingCategoryHasNonEmptyIcon() {
        for category in ShoppingCategory.allCases {
            #expect(!category.icon.isEmpty)
        }
    }

    @Test("all ShoppingCategory icon names are unique")
    func allShoppingCategoryIconNamesAreUnique() {
        let icons = ShoppingCategory.allCases.map(\.icon)
        let uniqueIcons = Set(icons)
        #expect(icons.count == uniqueIcons.count)
    }
}
