import Foundation
import GrowWiseModels
import SwiftData

// SwiftLint suppressions for #284 — pre-existing structural & style violations; refactor out of scope.
// swiftlint:disable line_length

/// Service that manages shopping list generation and persistence for gardens.
///
/// Uses auto-generation logic to suggest items based on garden composition,
/// plant growth stages, and care history. Also supports manual item management.
@MainActor
@Observable
public final class ShoppingListService {
    public init() {}

    // MARK: - Auto-Generation

    /// Generate shopping list items based on a garden's current plants and state.
    public func generateShoppingList(for garden: Garden, plants: [Plant]) -> [ShoppingItem] {
        var items: [ShoppingItem] = []
        items.append(contentsOf: generateSeedItems(for: garden, plants: plants))
        items.append(contentsOf: generateSoilItems(for: garden))
        items.append(contentsOf: generateFertilizerItems(for: garden, plants: plants))
        items.append(contentsOf: generateContainerItems(for: garden, plants: plants))
        items.append(contentsOf: generateToolItems(for: garden))
        return items
    }

    // MARK: - Persistence

    /// Fetch all shopping items for a given garden from the model context.
    public func fetchItems(for garden: Garden, context: ModelContext) -> [ShoppingItem] {
        let gardenID = garden.id
        let descriptor = FetchDescriptor<ShoppingItem>(
            predicate: #Predicate<ShoppingItem> { item in
                item.garden?.id == gardenID
            },
            sortBy: [
                SortDescriptor(\ShoppingItem.createdDate, order: .forward),
            ]
        )
        let fetched = (try? context.fetch(descriptor)) ?? []
        return fetched.sorted { lhs, rhs in
            if lhs.isPurchased != rhs.isPurchased {
                return !lhs.isPurchased
            }
            let lCat = lhs.category?.rawValue ?? ""
            let rCat = rhs.category?.rawValue ?? ""
            if lCat != rCat {
                return lCat < rCat
            }
            return (lhs.name ?? "") < (rhs.name ?? "")
        }
    }

    /// Toggle the purchased state of a shopping item.
    public func togglePurchased(_ item: ShoppingItem) {
        item.isPurchased.toggle()
    }

    /// Delete a shopping item from the model context.
    public func deleteItem(_ item: ShoppingItem, context: ModelContext) {
        context.delete(item)
    }

    // MARK: - Private Generation Helpers

    private func makeItem(
        name: String,
        category: ShoppingCategory,
        quantity: String,
        garden: Garden
    ) -> ShoppingItem {
        let item = ShoppingItem(name: name, category: category, quantity: quantity, isAutoGenerated: true)
        item.garden = garden
        return item
    }

    /// Seeds for plants still at seed/seedling stage.
    private func generateSeedItems(for garden: Garden, plants: [Plant]) -> [ShoppingItem] {
        plants
            .filter { $0.growthStage == nil || $0.growthStage == .seed || $0.growthStage == .seedling }
            .map { makeItem(name: "\($0.name ?? "Unknown") seeds", category: .seeds, quantity: "1 packet", garden: garden) }
    }

    /// Soil amendments based on garden type.
    private func generateSoilItems(for garden: Garden) -> [ShoppingItem] {
        switch garden.gardenType {
        case .raised:
            return [makeItem(name: "Raised bed soil mix", category: .soilAmendments, quantity: "2 bags", garden: garden)]

        case .container, .balcony, .windowsill:
            return [makeItem(name: "Potting soil", category: .soilAmendments, quantity: "1 bag", garden: garden)]

        case .indoor:
            return [makeItem(name: "Indoor potting mix", category: .soilAmendments, quantity: "1 bag", garden: garden)]

        case .hydroponic:
            return [makeItem(name: "Hydroponic nutrient solution", category: .soilAmendments, quantity: "1 bottle", garden: garden)]

        default:
            if garden.soilType == .clay || garden.soilType == .sand {
                return [makeItem(name: "Compost for soil amendment", category: .soilAmendments, quantity: "1 bag", garden: garden)]
            }
            return []
        }
    }

    /// Fertilizer if any plant needs feeding (last fertilized > 30 days ago or never).
    private func generateFertilizerItems(for garden: Garden, plants: [Plant]) -> [ShoppingItem] {
        guard !plants.isEmpty else { return [] }
        let thirtyDaysAgo = Calendar.current.date(byAdding: .day, value: -30, to: Date()) ?? Date()
        let needsFertilizer = plants.contains { plant in
            guard let lastFertilized = plant.lastFertilized else { return true }
            return lastFertilized < thirtyDaysAgo
        }
        guard needsFertilizer else { return [] }
        return [makeItem(name: "All-purpose fertilizer", category: .fertilizer, quantity: "1 bag", garden: garden)]
    }

    /// Containers for container-type gardens with plants missing container assignments.
    private func generateContainerItems(for garden: Garden, plants: [Plant]) -> [ShoppingItem] {
        let containerTypes: Set<GardenType> = [.container, .balcony, .windowsill]
        guard let gardenType = garden.gardenType, containerTypes.contains(gardenType) else { return [] }
        let count = plants.count(where: { $0.containerType == nil })
        guard count > 0 else { return [] }
        return [makeItem(name: "Plant containers", category: .containers, quantity: "\(count) pots", garden: garden)]
    }

    /// Basic tools if the garden was created within the last 14 days.
    private func generateToolItems(for garden: Garden) -> [ShoppingItem] {
        let fourteenDaysAgo = Calendar.current.date(byAdding: .day, value: -14, to: Date()) ?? Date()
        guard let created = garden.createdDate, created > fourteenDaysAgo else { return [] }
        return [
            makeItem(name: "Garden trowel", category: .tools, quantity: "1", garden: garden),
            makeItem(name: "Watering can", category: .tools, quantity: "1", garden: garden),
            makeItem(name: "Pruning shears", category: .tools, quantity: "1", garden: garden),
        ]
    }
}

// swiftlint:enable line_length
