import Foundation
@testable import GrowWiseModels
@testable import GrowWiseServices
import Testing

@MainActor
struct ShoppingListServiceTests {
    // MARK: - Helpers

    private func makeService() -> ShoppingListService {
        ShoppingListService()
    }

    private func makeGarden(type: GardenType = .outdoor, soilType: SoilType = .loam, createdDaysAgo: Int = 30) -> Garden {
        let garden = Garden(name: "Test Garden", gardenType: type)
        garden.soilType = soilType
        garden.createdDate = Calendar.current.date(byAdding: .day, value: -createdDaysAgo, to: Date())
        return garden
    }

    private func makePlant(name: String = "Tomato", growthStage: GrowthStage? = .vegetative, lastFertilized: Date? = Date(), containerType: ContainerType? = .container) -> Plant {
        let plant = Plant(name: name, plantType: .vegetable)
        plant.growthStage = growthStage
        plant.lastFertilized = lastFertilized
        plant.containerType = containerType
        return plant
    }

    // MARK: - generateShoppingList overall

    @Test("generateShoppingList returns empty list for garden with no trigger conditions")
    func generateShoppingListReturnsEmptyForNoTriggers() {
        let service = makeService()
        // outdoor loam garden created 30 days ago, mature plants fertilized recently
        let garden = makeGarden(type: .outdoor, soilType: .loam, createdDaysAgo: 30)
        let plant = makePlant(growthStage: .mature, lastFertilized: Date(), containerType: .inGround)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        #expect(items.isEmpty)
    }

    @Test("generateShoppingList returns items from multiple categories when multiple conditions are met")
    func generateShoppingListCombinesMultipleCategories() {
        let service = makeService()
        // new container garden (tools + containers + soil) with seedling needing seeds + no fertilizer
        let garden = makeGarden(type: .container, soilType: .loam, createdDaysAgo: 2)
        let plant = makePlant(growthStage: .seedling, lastFertilized: nil, containerType: nil)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        let categories = Set(items.compactMap(\.category))
        #expect(categories.contains(.seeds))
        #expect(categories.contains(.soilAmendments))
        #expect(categories.contains(.fertilizer))
        #expect(categories.contains(.containers))
        #expect(categories.contains(.tools))
    }

    @Test("all generated items are marked as auto-generated")
    func generatedItemsAreMarkedAutoGenerated() {
        let service = makeService()
        let garden = makeGarden(type: .raised, soilType: .loam, createdDaysAgo: 3)
        let plant = makePlant(growthStage: .seed, lastFertilized: nil, containerType: nil)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        #expect(!items.isEmpty)
        #expect(items.allSatisfy(\.isAutoGenerated))
    }

    @Test("all generated items have their garden set")
    func generatedItemsHaveGardenAssigned() {
        let service = makeService()
        let garden = makeGarden(type: .raised, soilType: .loam, createdDaysAgo: 3)
        let plant = makePlant(growthStage: .seed, lastFertilized: nil, containerType: nil)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        #expect(!items.isEmpty)
        #expect(items.allSatisfy { $0.garden?.id == garden.id })
    }

    // MARK: - Seed Generation

    @Test("seed stage plant triggers a seed item")
    func seedStagePlantTriggersSeedItem() {
        let service = makeService()
        let garden = makeGarden()
        let plant = makePlant(name: "Basil", growthStage: .seed, lastFertilized: Date(), containerType: .inGround)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        let seedItems = items.filter { $0.category == .seeds }
        #expect(seedItems.count == 1)
        #expect(seedItems.first?.name == "Basil seeds")
    }

    @Test("seedling stage plant triggers a seed item")
    func seedlingStagePlantTriggersSeedItem() {
        let service = makeService()
        let garden = makeGarden()
        let plant = makePlant(name: "Pepper", growthStage: .seedling, lastFertilized: Date(), containerType: .inGround)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        let seedItems = items.filter { $0.category == .seeds }
        #expect(seedItems.count == 1)
        #expect(seedItems.first?.name == "Pepper seeds")
    }

    @Test("plant with nil growthStage triggers a seed item")
    func nilGrowthStagePlantTriggersSeedItem() {
        let service = makeService()
        let garden = makeGarden()
        let plant = makePlant(name: "Mystery Plant", growthStage: nil, lastFertilized: Date(), containerType: .inGround)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        let seedItems = items.filter { $0.category == .seeds }
        #expect(seedItems.count == 1)
    }

    @Test("mature plant does not trigger a seed item")
    func maturePlantDoesNotTriggerSeedItem() {
        let service = makeService()
        let garden = makeGarden()
        let plant = makePlant(growthStage: .mature, lastFertilized: Date(), containerType: .inGround)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        let seedItems = items.filter { $0.category == .seeds }
        #expect(seedItems.isEmpty)
    }

    @Test("vegetative plant does not trigger a seed item")
    func vegetativePlantDoesNotTriggerSeedItem() {
        let service = makeService()
        let garden = makeGarden()
        let plant = makePlant(growthStage: .vegetative, lastFertilized: Date(), containerType: .inGround)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        let seedItems = items.filter { $0.category == .seeds }
        #expect(seedItems.isEmpty)
    }

    @Test("two seedling plants produce two separate seed items")
    func twoSeedlingsProdduceTwoSeedItems() {
        let service = makeService()
        let garden = makeGarden()
        let basil = makePlant(name: "Basil", growthStage: .seedling, lastFertilized: Date(), containerType: .inGround)
        let mint = makePlant(name: "Mint", growthStage: .seedling, lastFertilized: Date(), containerType: .inGround)
        let items = service.generateShoppingList(for: garden, plants: [basil, mint])
        let seedItems = items.filter { $0.category == .seeds }
        #expect(seedItems.count == 2)
    }

    @Test("seed item quantity is 1 packet")
    func seedItemQuantityIsOnePacket() {
        let service = makeService()
        let garden = makeGarden()
        let plant = makePlant(growthStage: .seed, lastFertilized: Date(), containerType: .inGround)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        let seedItem = try #require(items.filter { $0.category == .seeds }.first)
        #expect(seedItem.quantity == "1 packet")
    }

    // MARK: - Soil Generation

    @Test("raised garden generates raised bed soil mix")
    func raisedGardenGeneratesRaisedBedSoil() {
        let service = makeService()
        let garden = makeGarden(type: .raised)
        let items = service.generateShoppingList(for: garden, plants: [])
        let soilItems = items.filter { $0.category == .soilAmendments }
        #expect(soilItems.count == 1)
        #expect(soilItems.first?.name == "Raised bed soil mix")
        #expect(soilItems.first?.quantity == "2 bags")
    }

    @Test("container garden generates potting soil")
    func containerGardenGeneratesPottingSoil() {
        let service = makeService()
        let garden = makeGarden(type: .container)
        let items = service.generateShoppingList(for: garden, plants: [])
        let soilItems = items.filter { $0.category == .soilAmendments }
        #expect(soilItems.count == 1)
        #expect(soilItems.first?.name == "Potting soil")
        #expect(soilItems.first?.quantity == "1 bag")
    }

    @Test("balcony garden generates potting soil")
    func balconyGardenGeneratesPottingSoil() {
        let service = makeService()
        let garden = makeGarden(type: .balcony)
        let items = service.generateShoppingList(for: garden, plants: [])
        let soilItems = items.filter { $0.category == .soilAmendments }
        #expect(soilItems.count == 1)
        #expect(soilItems.first?.name == "Potting soil")
    }

    @Test("windowsill garden generates potting soil")
    func windowsillGardenGeneratesPottingSoil() {
        let service = makeService()
        let garden = makeGarden(type: .windowsill)
        let items = service.generateShoppingList(for: garden, plants: [])
        let soilItems = items.filter { $0.category == .soilAmendments }
        #expect(soilItems.count == 1)
        #expect(soilItems.first?.name == "Potting soil")
    }

    @Test("indoor garden generates indoor potting mix")
    func indoorGardenGeneratesIndoorPottingMix() {
        let service = makeService()
        let garden = makeGarden(type: .indoor)
        let items = service.generateShoppingList(for: garden, plants: [])
        let soilItems = items.filter { $0.category == .soilAmendments }
        #expect(soilItems.count == 1)
        #expect(soilItems.first?.name == "Indoor potting mix")
    }

    @Test("hydroponic garden generates nutrient solution")
    func hydroponicGardenGeneratesNutrientSolution() {
        let service = makeService()
        let garden = makeGarden(type: .hydroponic)
        let items = service.generateShoppingList(for: garden, plants: [])
        let soilItems = items.filter { $0.category == .soilAmendments }
        #expect(soilItems.count == 1)
        #expect(soilItems.first?.name == "Hydroponic nutrient solution")
    }

    @Test("outdoor garden with clay soil generates compost amendment")
    func outdoorClaySoilGeneratesCompostAmendment() {
        let service = makeService()
        let garden = makeGarden(type: .outdoor, soilType: .clay)
        let items = service.generateShoppingList(for: garden, plants: [])
        let soilItems = items.filter { $0.category == .soilAmendments }
        #expect(soilItems.count == 1)
        #expect(soilItems.first?.name == "Compost for soil amendment")
    }

    @Test("outdoor garden with sand soil generates compost amendment")
    func outdoorSandSoilGeneratesCompostAmendment() {
        let service = makeService()
        let garden = makeGarden(type: .outdoor, soilType: .sand)
        let items = service.generateShoppingList(for: garden, plants: [])
        let soilItems = items.filter { $0.category == .soilAmendments }
        #expect(soilItems.count == 1)
        #expect(soilItems.first?.name == "Compost for soil amendment")
    }

    @Test("outdoor garden with good loam soil generates no soil items")
    func outdoorLoamSoilGeneratesNoSoilItems() {
        let service = makeService()
        let garden = makeGarden(type: .outdoor, soilType: .loam)
        let items = service.generateShoppingList(for: garden, plants: [])
        let soilItems = items.filter { $0.category == .soilAmendments }
        #expect(soilItems.isEmpty)
    }

    // MARK: - Fertilizer Generation

    @Test("plant never fertilized triggers fertilizer item")
    func plantNeverFertilizedTriggersFertilizer() {
        let service = makeService()
        let garden = makeGarden()
        let plant = makePlant(growthStage: .mature, lastFertilized: nil, containerType: .inGround)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        let fertItems = items.filter { $0.category == .fertilizer }
        #expect(fertItems.count == 1)
        #expect(fertItems.first?.name == "All-purpose fertilizer")
    }

    @Test("plant fertilized 31 days ago triggers fertilizer item")
    func plantFertilized31DaysAgoTriggersFertilizer() throws {
        let service = makeService()
        let garden = makeGarden()
        let oldDate = try #require(Calendar.current.date(byAdding: .day, value: -31, to: Date()))
        let plant = makePlant(growthStage: .mature, lastFertilized: oldDate, containerType: .inGround)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        let fertItems = items.filter { $0.category == .fertilizer }
        #expect(fertItems.count == 1)
    }

    @Test("plant fertilized today does not trigger fertilizer item")
    func plantFertilizedTodayDoesNotTriggerFertilizer() {
        let service = makeService()
        let garden = makeGarden()
        let plant = makePlant(growthStage: .mature, lastFertilized: Date(), containerType: .inGround)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        let fertItems = items.filter { $0.category == .fertilizer }
        #expect(fertItems.isEmpty)
    }

    @Test("plant fertilized 29 days ago does not trigger fertilizer item")
    func plantFertilized29DaysAgoDoesNotTriggerFertilizer() throws {
        let service = makeService()
        let garden = makeGarden()
        let recentDate = try #require(Calendar.current.date(byAdding: .day, value: -29, to: Date()))
        let plant = makePlant(growthStage: .mature, lastFertilized: recentDate, containerType: .inGround)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        let fertItems = items.filter { $0.category == .fertilizer }
        #expect(fertItems.isEmpty)
    }

    @Test("empty plant list generates no fertilizer item")
    func emptyPlantListGeneratesNoFertilizer() {
        let service = makeService()
        let garden = makeGarden()
        let items = service.generateShoppingList(for: garden, plants: [])
        let fertItems = items.filter { $0.category == .fertilizer }
        #expect(fertItems.isEmpty)
    }

    @Test("only one fertilizer item is generated even when multiple plants need fertilizing")
    func oneFertilizerItemForMultipleNeedyPlants() {
        let service = makeService()
        let garden = makeGarden()
        let p1 = makePlant(name: "Tomato", growthStage: .mature, lastFertilized: nil, containerType: .inGround)
        let p2 = makePlant(name: "Basil", growthStage: .mature, lastFertilized: nil, containerType: .inGround)
        let items = service.generateShoppingList(for: garden, plants: [p1, p2])
        let fertItems = items.filter { $0.category == .fertilizer }
        #expect(fertItems.count == 1)
    }

    @Test("fertilizer item quantity is 1 bag")
    func fertilizerItemQuantityIsOneBag() {
        let service = makeService()
        let garden = makeGarden()
        let plant = makePlant(growthStage: .mature, lastFertilized: nil, containerType: .inGround)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        let fertItem = try #require(items.filter { $0.category == .fertilizer }.first)
        #expect(fertItem.quantity == "1 bag")
    }

    // MARK: - Container Generation

    @Test("container garden with plant missing containerType generates container item")
    func containerGardenWithUnassignedPlantGeneratesContainerItem() {
        let service = makeService()
        let garden = makeGarden(type: .container)
        let plant = makePlant(growthStage: .vegetative, lastFertilized: Date(), containerType: nil)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        let containerItems = items.filter { $0.category == .containers }
        #expect(containerItems.count == 1)
        #expect(containerItems.first?.quantity == "1 pots")
    }

    @Test("container garden with 3 plants missing containerType generates 3 pots quantity")
    func containerGardenWithThreeUnassignedPlantsGeneratesThreePots() {
        let service = makeService()
        let garden = makeGarden(type: .container)
        let plants = (1 ... 3).map { _ in makePlant(growthStage: .vegetative, lastFertilized: Date(), containerType: nil) }
        let items = service.generateShoppingList(for: garden, plants: plants)
        let containerItems = items.filter { $0.category == .containers }
        #expect(containerItems.count == 1)
        #expect(containerItems.first?.quantity == "3 pots")
    }

    @Test("container garden with all plants having containerType generates no container item")
    func containerGardenWithAllAssignedPlantsGeneratesNoContainerItem() {
        let service = makeService()
        let garden = makeGarden(type: .container)
        let plant = makePlant(growthStage: .vegetative, lastFertilized: Date(), containerType: .container)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        let containerItems = items.filter { $0.category == .containers }
        #expect(containerItems.isEmpty)
    }

    @Test("balcony garden with plant missing containerType generates container item")
    func balconyGardenWithUnassignedPlantGeneratesContainerItem() {
        let service = makeService()
        let garden = makeGarden(type: .balcony)
        let plant = makePlant(growthStage: .vegetative, lastFertilized: Date(), containerType: nil)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        let containerItems = items.filter { $0.category == .containers }
        #expect(containerItems.count == 1)
    }

    @Test("windowsill garden with plant missing containerType generates container item")
    func windowsillGardenWithUnassignedPlantGeneratesContainerItem() {
        let service = makeService()
        let garden = makeGarden(type: .windowsill)
        let plant = makePlant(growthStage: .vegetative, lastFertilized: Date(), containerType: nil)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        let containerItems = items.filter { $0.category == .containers }
        #expect(containerItems.count == 1)
    }

    @Test("outdoor garden with plant missing containerType does not generate container item")
    func outdoorGardenDoesNotGenerateContainerItem() {
        let service = makeService()
        let garden = makeGarden(type: .outdoor)
        let plant = makePlant(growthStage: .vegetative, lastFertilized: Date(), containerType: nil)
        let items = service.generateShoppingList(for: garden, plants: [plant])
        let containerItems = items.filter { $0.category == .containers }
        #expect(containerItems.isEmpty)
    }

    // MARK: - Tool Generation

    @Test("garden created today generates 3 starter tool items")
    func gardenCreatedTodayGeneratesThreeToolItems() {
        let service = makeService()
        let garden = makeGarden(type: .outdoor, createdDaysAgo: 0)
        let items = service.generateShoppingList(for: garden, plants: [])
        let toolItems = items.filter { $0.category == .tools }
        #expect(toolItems.count == 3)
    }

    @Test("garden created 13 days ago still generates tool items")
    func gardenCreated13DaysAgoGeneratesToolItems() {
        let service = makeService()
        let garden = makeGarden(type: .outdoor, createdDaysAgo: 13)
        let items = service.generateShoppingList(for: garden, plants: [])
        let toolItems = items.filter { $0.category == .tools }
        #expect(toolItems.count == 3)
    }

    @Test("garden created 15 days ago does not generate tool items")
    func gardenCreated15DaysAgoDoesNotGenerateToolItems() {
        let service = makeService()
        let garden = makeGarden(type: .outdoor, createdDaysAgo: 15)
        let items = service.generateShoppingList(for: garden, plants: [])
        let toolItems = items.filter { $0.category == .tools }
        #expect(toolItems.isEmpty)
    }

    @Test("new garden tools include trowel, watering can, and pruning shears")
    func newGardenToolsAreCorrectItems() {
        let service = makeService()
        let garden = makeGarden(type: .outdoor, createdDaysAgo: 1)
        let items = service.generateShoppingList(for: garden, plants: [])
        let toolNames = Set(items.filter { $0.category == .tools }.compactMap(\.name))
        #expect(toolNames.contains("Garden trowel"))
        #expect(toolNames.contains("Watering can"))
        #expect(toolNames.contains("Pruning shears"))
    }

    @Test("tool items each have quantity of 1")
    func toolItemsHaveQuantityOfOne() {
        let service = makeService()
        let garden = makeGarden(type: .outdoor, createdDaysAgo: 1)
        let items = service.generateShoppingList(for: garden, plants: [])
        let toolItems = items.filter { $0.category == .tools }
        #expect(toolItems.allSatisfy { $0.quantity == "1" })
    }

    // MARK: - togglePurchased

    @Test("togglePurchased flips unpurchased item to purchased")
    func togglePurchasedFlipsToTrue() {
        let service = makeService()
        let item = ShoppingItem(name: "Fertilizer", category: .fertilizer)
        #expect(item.isPurchased == false)
        service.togglePurchased(item)
        #expect(item.isPurchased == true)
    }

    @Test("togglePurchased flips purchased item back to unpurchased")
    func togglePurchasedFlipsBackToFalse() {
        let service = makeService()
        let item = ShoppingItem(name: "Fertilizer", category: .fertilizer)
        item.isPurchased = true
        service.togglePurchased(item)
        #expect(item.isPurchased == false)
    }

    @Test("toggling twice restores original purchased state")
    func togglePurchasedTwiceRestoresOriginalState() {
        let service = makeService()
        let item = ShoppingItem(name: "Seeds", category: .seeds)
        service.togglePurchased(item)
        service.togglePurchased(item)
        #expect(item.isPurchased == false)
    }

    @Test("toggling one item does not affect another item's purchased state")
    func togglePurchasedDoesNotAffectOtherItems() {
        let service = makeService()
        let item1 = ShoppingItem(name: "Seeds", category: .seeds)
        let item2 = ShoppingItem(name: "Tools", category: .tools)
        service.togglePurchased(item1)
        #expect(item1.isPurchased == true)
        #expect(item2.isPurchased == false)
    }
}
