name: CI

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run lint
        run: npm run lint

  format:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run format
        run: npm run format

  test:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: npm test

  sonarcloud:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sonarcloud scan
        run: npm run sonar

  dead-code:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check for dead code
        run: npm run dead-code
